common: &common
  adapter: postgresql
  username: rails
  password: password
  host: localhost
  port: 6543

development:
  <<: *common
  database: rails_development

test:
  <<: *common
  database: rails_test

production:
  <<: *common
  database: rails_production
